package uk.ac.cam.cl.intelligentgamedesigner.leveldesigner;

import java.util.Random;

import uk.ac.cam.cl.intelligentgamedesigner.coregame.Design;

public abstract class LevelRepresentation implements Cloneable {
	protected Random random;
	
	public LevelRepresentation(Random r) {
		random = r;
	}
	
	public LevelRepresentation clone() {
		LevelRepresentation clone = null;
		try {
			clone = (LevelRepresentation) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return clone;
	}
	
	/**
	 * Slightly alters the level representation.
	 */
	public abstract void mutate();
	
	/**
	 * Performs crossover using the given LevelRepresentation and this.
	 * Returns a two item array of the children generated by the crossover.
	 * @param parent the other parent to use when performing crossover.
	 * @return a two item array of the children.
	 */
	public abstract LevelRepresentation[] crossoverWith(LevelRepresentation parent);
	
	public abstract Design getDesign();
	
	public abstract double getAestheticFitness();
}
